name: Automatic Testing for Project

on:
  push:
    branches:
      - final-branch # Trigger the workflow on push to final-branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from GitHub Repo
      uses: actions/checkout@v3

    - name: Setup Node.js in Ubuntu
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Remove existing node_modules folder from cloned project
      run: rm -rf /home/runner/work/DevOps-Project-daryl/DevOps-Project-daryl/node_modules/*

    - name: Install dependencies based on package.json
      run: npm install

    - name: Run backend tests and generate coverage
      run: npm run backend-test

    - name: Run frontend tests and generate coverage
      run: npm run frontend-test
